unisystem_frontpage_main:
    path:     /
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:main }

unisystem_frontpage_member:
    path:     /member
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:member }

unisystem_frontpage_officer:
    path:     /officer
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:officer }

unisystem_frontpage_academy:
    path:     /academy
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:academy }

unisystem_frontpage_resource:
    path:     /resource
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:resource }

unisystem_frontpage_notice:
    path:     /notice
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:notice }

unisystem_frontpage_history:
    path:     /history
    defaults: { _controller: UnisystemFrontpageBundle:Frontpage:history }
