unisystem_admin_notice:
    resource: "@UnisystemAdminBundle/Resources/config/routing/notice.yml"
    prefix:   /notice

unisystem_admin_member:
    resource: "@UnisystemAdminBundle/Resources/config/routing/member.yml"
    prefix:   /member/index

unisystem_admin_member_course:
    resource: "@UnisystemAdminBundle/Resources/config/routing/membercourse.yml"
    prefix:   /member/course

unisystem_admin_member_role:
    resource: "@UnisystemAdminBundle/Resources/config/routing/memberrole.yml"
    prefix:   /member/role

unisystem_admin_history:
    resource: "@UnisystemAdminBundle/Resources/config/routing/history.yml"
    prefix:   /history

unisystem_admin_resource:
    resource: "@UnisystemAdminBundle/Resources/config/routing/resource.yml"
    prefix:   /resource

unisystem_admin_academy:
    resource: "@UnisystemAdminBundle/Resources/config/routing/academy.yml"
    prefix:   /academy

unisystem_admin_main_photography:
    resource: "@UnisystemAdminBundle/Resources/config/routing/mainphotography.yml"
    prefix:   /mainphotography

unisystem_admin_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/notice
        permanent: true