services:
    unisystem_member.form.type.fileinput:
        class: Unisystem\UploadBundle\Form\UploadType
        arguments: ['@vich_uploader.storage', '@vich_uploader.upload_handler', '@translator']
        tags:
            - { name: form.type, alias: fileinput }
#    unisystem_member.example:
#        class: Unisystem\MemberBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
